### ISSUE TITLE
v115 looping and Overlay window issue

### ISSUE THREAD

**Issue by Montigrom** [ffxivcode/AutoDuty#200]
Addon won't start new loop after ending a dungeon also small overlay window disappeared.

**Comment by filipinopepper** [comment]
Adding more information to this - the loop I have was set to 20 times and it finished the dungeon but it never queued back in even with a delay of 10 seconds for the "Support" dungeons. 
![image](https://github.com/user-attachments/assets/170167ad-4a7f-4b4e-a21d-bf5f6d70c98e)

**Comment by sjil** [comment]
Also getting this problem, any way to revert an update xD

**Comment by BGFY91** [comment]
The problem is caused by some change to the `Auto Equip Recommended Gear` feature that causes it to hang. Disable it for the time being and it will resume looping correctly.

On a semi related note, additional wait time needs to be added after eating a Boiled Egg because currently the attempt to Repair via Self gets blocked by being busy. This wasn't an issue before I guess because you didn't eat an egg every run, so on the runs that you didn't it would successfully repair, but now it won't succeed unless you run out of eggs.
