### ISSUE TITLE
[Path] Ihuykatumu and Worqor Zormor

### ISSUE THREAD

**Issue by chaosgobbie** [ffxivcode/AutoDuty#55]
I've been using these with Duty Support with good results.

In these dungeons the shortcut updates to just before the boss once it is pulled so it does not start at the previous arena on a wipe.  As a result, I had to add a Boss|0,0,0| before each boss to act as a checkpoint.  Unfortunately, that adds a delay while the Boss command is timing out but it doesn't break everything when you wipe on a boss with all the launch pads, ladders and ledges in these dungeons.  Perhaps a Checkpoint action or an instant timeout option on the Boss action would be a good addition?

Thanks
 
(1167) Ihuykatumu.json
["MoveTo|-69.48, -194.00, -32.38|","Wait|0, 0, 0|60000","MoveTo|-59.19, -194.17, -31.57|","ChatCommand|-59.19, -194.17, -31.57|/automove on boat","Wait|0, 0, 0|1000","ChatCommand|0, 0, 0|/automove off boat","Boss|0,0,0|","Boss|34.26, -203.00, -101.55|","MoveTo|149.89, -195.06, -20.28|","MoveTo|148.41, -195.49, -33.19|","MoveTo|150.75, -195.42, -30.44|","ChatCommand|0, 0, 0|/automove on l1","Wait|0, 0, 0|10000","ChatCommand|0, 0, 0|/automove off l1","MoveTo|203.19, -158.65, 116.40|","MoveTo|140.08, -155.07, 113.95|","MoveTo|149.45, -155.46, 114.70|","MoveTo|134.77, -154.87, 113.17|","ChatCommand|0, 0, 0|/automove on l2","Wait|0, 0, 0|10000","ChatCommand|0, 0, 0|/automove off l2","Boss|0,0,0|","Boss|79.96, -134.00, 48.86|","MoveTo|66.54, -134.00, 40.44|","MoveTo|39.96, -130.76, 37.28|","ChatCommand|0, 0, 0|/automove on l3","Wait|0, 0, 0|10000","ChatCommand|0, 0, 0|/automove off l3","MoveTo|11.17, -110.85, 149.02|","MoveTo|-97.40, -115.20, 336.53|","Boss|0,0,0|","Boss|-106.82, -118.00, 263.31|","MoveTo|-106.73, -118.00, 253.11|"]

(1193) Worqor Zormor.json
["MoveTo|-7.21, -2.81, 189.66|","MoveTo|-65.31, 1.12, 205.48|","Boss|0, 0, 0|","Boss|-108.32, 11.00, 118.76|","MoveTo|-108.02, 11.00, 102.98|","MoveTo|-144.25, 22.12, 76.17|","MoveTo|-68.00, 40.00, 53.93|","MoveTo|-65.51, 40.17, 53.33|","ChatCommand|0, 0, 0|/automove on jp1","Wait|0, 0, 0|6000","ChatCommand|0, 0, 0|/automove off jp1","MoveTo|-41.11, 55.08, 26.01|","Wait|0, 0, 0|6000","MoveTo|-46.11, 55.15, 20.30|","MoveTo|-46.98, 55.45, 19.27|","ChatCommand|0, 0, 0|/automove on jp2","Wait|0, 0, 0|6000","ChatCommand|0, 0, 0|/automove off jp2","MoveTo|-79.49, 85.08, 11.86|","MoveTo|-81.35, 85.13, 13.32|","ChatCommand|0, 0, 0|/automove on ledge","Wait|0, 0, 0|5000","ChatCommand|0, 0, 0|/automove off ledge","MoveTo|-94.76, 70.00, 48.33|","MoveTo|-99.78, 70.00, 42.46|","MoveTo|-101.68, 70.00, 42.62|","ChatCommand|0, 0, 0|/automove on jp3","Wait|0, 0, 0|6000","ChatCommand|0, 0, 0|/automove off jp3","MoveTo|-160.77, 80.03, 34.43|","MoveTo|-63.83, 101.63, -15.98|","MoveTo|-61.40, 102.66, -17.23|","ChatCommand|0, 0, 0|/automove on jp4","Wait|0, 0, 0|13000","ChatCommand|0, 0, 0|/automove off jp4","Boss|0, 0, 0|","Boss|-52.64, 323.00, -57.39|","MoveTo|-68.98, 323.00, -56.92|","MoveTo|-120.75, 328.00, -83.00|","MoveTo|-153.35, 334.71, 0.80|","MoveTo|-69.44, 358.07, -91.74|","Boss|0, 0, 0|","Boss|-53.54, 378.00, -195.05|","MoveTo|-54.01, 378.00, -213.26|"]

**Comment by adambennett55** [comment]
How are these compared to the ones added in PR #58 by VeraNala?

**Comment by alyssadev** [comment]
The above PR doesn't have Worqor Zormor

**Comment by VeraNala** [comment]
I accidentally missed the 1193 file when I was uploading #58 but have since included it and it's been merged. (Really sorry about that!!)

Comparing the paths I think they're more or less equally viable, but I'm seeing a few potential pitfalls here that that I've tried to consider and remedy in my own paths.
(Please don't take this as me tearing apart your path I think it's very well done and I appreciate you following my makeshift format haha, I just want to share my own findings should you find any merit in them for your future pathing.) \o/
And bear in mind I'm only glancing at the steps, not running the path itself, ingame to check coordinate accuracy or anything.

> (1167) Ihuykatumu.json
 - The Wait 60000 step is something I found that I had to split apart into multiple steps -> For whatever reason, AD will proceed with the wait timer even if the player is in combat, meaning that consistency might depend on how fast or slow the player kills enemies. When it's broken up, waits will expire as enemies appear and the player enters combat, but not move onto the next wait step until the player exits combat.
 - The following MoveTo and Chatcommand share coordinates. Consider playing as a ranged or a caster who stays at the back of the boat throughout the entire encounter - or dodges AoE's in a manner that places them offset from the boat's exit. Using a single coordinate means that there is no "line up" before starting the autorun, which makes me question whether or not the character will properly exit the boat. I typically try and make use of 2 points, to ensure that the player is moving in a straight line prior to starting the automove. (Unless of course, your coordinates are at the boat's edge, in which case, it will likely work as expected!)
 - I appreciate you making use of my idea of checkpoints via boss steps! Bear in mind that they can have coordinates (I've been placing mine just before the boss arena in most cases, or at known shortcut/revive spots) and that *notes* can be added to them (I use CP1, CP2, etc) I've also thought about and agree wholeheartedly that having them as a separate "checkpoint" step that doesn't require time would be quite ideal, hopefully in a future version of AD? =D
 - Automove off steps are technically not required after a loss-of-control transition such as the ladder climbs, super minor and not an issue, just mentioning to save you some potential headaches/effort.
 
 > (1193) Worqor Zormor.json
  - The ledge you're referring to doesn't technically require an Automove, but I understand why you included it. It is considered one complete mesh as per vnav and navigation down it works just fine.
  - Personally, I ran into a consistency issue with the second jump pad, in that it has a delayed trigger, and small enough activation area that you can automove completely through and over it without it ever activating -> For this I reverted back to using a positional wait step ontop of the pad in my path. The other pads do not have this issue as they are adjacent to walls, thankfully.
  - The Boss Checkpoint and Automove Off things, again. (Which again, isn't anything major)

All in all though I think the paths are great! I would've been pretty happy with them if I hadn't already made some!
Heck, at first glance I thought they *WERE* my paths with how similar they are XD
Awesome job! (I'll let you handle the next dungeon, yeah?) =D

**Comment by chaosgobbie** [comment]
I'm not too committed to the paths or making them.  I only therw them together because I needed them and threw em up because I hadn't seen any posted yet.  I almost deleted the issue when I saw your pull request pop up after.

As long as one that works is in the release, I'm good.  ;)
